sds:
  networkAddress: 127.0.0.1
  apiPort: 8081
  clientPort: 8888
  websocketPort: 8889
  connectionRetries:
    max: 100
    sleepDuration: 3000 # milliseconds
stratosChain:
  restServer: http://127.0.0.1:1317
  websocketServer: 127.0.0.1:26657
  connectionRetries:
    max: 100
    sleepDuration: 3000 # milliseconds
blockchainInfo:
  addressPrefix: st
  p2pAddressPrefix: stsdsp2p
  chainId: test-chain
  token: ustos